### ISSUE TITLE
Please make a "Rock Paper Scissors" Game

### ISSUE THREAD

**Issue by mahadi22** [mahadi22/Collection-of-Script#28]
If anyone interested, please make a simple "Rock Paper Scissors" Game in any programming language you can and merge to here.

**Comment by Harshil-Jani** [comment]
Can I have a try with JavaScript ? @mahadi22

**Comment by ahmadfaizan965** [comment]
Would python be okay ?

**Comment by mahadi22** [comment]
> Can I have a try with JavaScript ? @mahadi22

> Would python be okay ?

yes you can do that

**Comment by ssurbhi09** [comment]
Can I make it In python
Please assign me!

**Comment by mahadi22** [comment]
> Can I make it In python Please assign me!

approved
