### ISSUE TITLE
Please make a "Tic Tac Toe" Game

### ISSUE THREAD

**Issue by mahadi22** [mahadi22/Collection-of-Script#30]
If anyone interested, please make a "Tic Tac Toe" Game in any programming language you can and merge to here.

**Comment by BudiRahmawan** [comment]
i can do that in Python

**Comment by mahadi22** [comment]
> i can do that in Python

thank you, you can do this issue

**Comment by BudiRahmawan** [comment]
Done, i hope this script can help anyone out there
